/// Generated by AssetsRefGenerator on 2022/10/05
class Res {
  static const String ar = "assets/lang/ar.json";
  static const String bg = "assets/images/bg.png";
  static const String chec = "assets/images/chec.png";
  static const String en = "assets/lang/en.json";
  static const String faceIcon = "assets/images/faceIcon.png";
  static const String following = "assets/images/following.png";
  static const String hands = "assets/images/hands.png";
  static const String ingredients = "assets/images/ingredients.png";
  static const String intro_one = "assets/images/intro_one.png";
  static const String intro_three = "assets/images/intro_three.png";
  static const String intro_two = "assets/images/intro_two.png";
  static const String logo = "assets/images/logo.png";
  static const String mailIcon = "assets/images/mailIcon.png";
  static const String marker = "assets/images/marker.png";
  static const String nodata = "assets/images/nodata.png";
  static const String placeholder = "assets/images/placeholder.png";
  static const String plus = "assets/images/plus.png";
  static const String ProximaNova_Bold = "assets/fonts/ProximaNova-Bold.otf";
  static const String ProximaNova_Regular = "assets/fonts/ProximaNova-Regular.otf";
  static const String splash = "assets/images/splash.png";
  static const String warning = "assets/images/warning.png";
}
